# Generated by Django 5.0.2 on 2024-03-04 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyberfx', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expertadvisor',
            old_name='name',
            new_name='ea_name',
        ),
        migrations.RemoveField(
            model_name='expertadvisor',
            name='description',
        ),
        migrations.RemoveField(
            model_name='expertadvisor',
            name='performance_data',
        ),
        migrations.AddField(
            model_name='expertadvisor',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='expertadvisor',
            name='lessons_learned',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expertadvisor',
            name='number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='expertadvisor',
            name='personal_review',
            field=models.TextField(blank=True, null=True),
        ),
    ]
