# Generated by Django 5.0.2 on 2024-03-11 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cyberfx', '0002_rename_name_expertadvisor_ea_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expertadvisor',
            name='lessons_learned',
        ),
    ]
