# Generated by Django 5.0.2 on 2024-03-11 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyberfx', '0003_remove_expertadvisor_lessons_learned'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertadvisor',
            name='category',
            field=models.CharField(choices=[('Trash', 'Trash'), ('Testing', 'Testing'), ('Good', 'Good')], default='Trash', max_length=10),
        ),
    ]
