# Generated by Django 5.0.2 on 2024-03-11 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cyberfx', '0004_expertadvisor_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expertadvisor',
            name='number',
        ),
    ]
