# Generated by Django 5.0.2 on 2024-03-11 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyberfx', '0005_remove_expertadvisor_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertadvisor',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
