# Generated by Django 5.0.2 on 2024-03-11 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyberfx', '0006_expertadvisor_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='posted_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
