# Generated by Django 5.0.2 on 2024-03-21 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyberfx', '0008_expertadvisor_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertadvisor',
            name='category',
            field=models.CharField(choices=[('Trash', 'Trash'), ('Testing', 'Testing'), ('Goodfornow', 'Goodfornow')], default='Trash', max_length=20),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
